Get actual resource URL if 404
datagouv/hydra pull request #225
Opened 2024-11-21 12:54 UTC by Pierlou

Fix https://github.com/datagouv/data.gouv.fr/issues/1574 / https://github.com/datagouv/hydra/issues/224

2024-11-21 16:26 UTC, bolinocroustibat requested changes

2024-11-21 16:41 UTC, Pierlou commented on udata_hydra/crawl/check_resources.py
> +        if getattr(e, "status", None) == 404:
I was desperately hoping we could skip that part haha I'll do that

2024-11-21 16:43 UTC, Pierlou commented on udata_hydra/crawl/check_resources.py
> +        # if we get a 404, it might be that the resource's URL has changed since last catalog load
Agreed, this was a first draft to see if we agreed on the workflow, I can wrap it more elegantly ✨

2024-11-22 10:16 UTC, maudetes approved these changes
:pray: it's quite light actually, well done!

2024-11-26 14:59 UTC, merged